#!/usr/bin/env python3
"""Prepare a Windows embeddable CPython runtime for HakureiTerminal.

The generated runtime layout is compatible with the Dart bridge lookup:

    <python-root>/runtime/python.exe
    <python-root>/runtime/python314.zip
    <python-root>/runtime/Lib/site-packages/...

The script downloads the official Windows embeddable CPython zip, enables
``import site`` in the generated ``._pth`` file, bootstraps pip with get-pip.py,
and installs project requirements into the runtime site-packages directory.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VERSION = "3.14.0"
DEFAULT_ARCH = "amd64"
DEFAULT_CACHE_DIR = ROOT / ".cache" / "python-runtime"
DEFAULT_TARGET = ROOT / "hakureiterminal" / "assets" / "python" / "runtime"
GET_PIP_URL = "https://bootstrap.pypa.io/get-pip.py"


def embeddable_url(version: str, arch: str) -> str:
    return f"https://www.python.org/ftp/python/{version}/python-{version}-embed-{arch}.zip"


def download(url: str, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        print(f"Using cached {target}")
        return
    print(f"Downloading {url}")
    urllib.request.urlretrieve(url, target)


def extract_runtime(zip_path: Path, target: Path, clean: bool) -> None:
    if clean and target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path) as archive:
        archive.extractall(target)


def enable_site(runtime_dir: Path) -> None:
    pth_files = sorted(runtime_dir.glob("python*._pth"))
    if not pth_files:
        raise FileNotFoundError(f"Cannot find python*._pth in {runtime_dir}")
    for pth_file in pth_files:
        lines = pth_file.read_text(encoding="utf-8").splitlines()
        updated: list[str] = []
        has_site_packages = False
        has_import_site = False
        for line in lines:
            stripped = line.strip()
            if stripped == "Lib/site-packages":
                has_site_packages = True
            if stripped in {"import site", "#import site"}:
                updated.append("import site")
                has_import_site = True
            else:
                updated.append(line)
        if not has_site_packages:
            updated.append("Lib/site-packages")
        if not has_import_site:
            updated.append("import site")
        pth_file.write_text("\n".join(updated) + "\n", encoding="utf-8")


def run(command: list[str], cwd: Path | None = None) -> None:
    print("Running:", " ".join(command))
    subprocess.run(command, cwd=cwd, check=True)


def bootstrap_pip(runtime_dir: Path, cache_dir: Path) -> None:
    python_exe = runtime_dir / "python.exe"
    if not python_exe.exists():
        raise FileNotFoundError(f"Cannot find {python_exe}")

    get_pip = cache_dir / "get-pip.py"
    download(GET_PIP_URL, get_pip)
    run([str(python_exe), str(get_pip), "--no-warn-script-location"])


def install_requirements(
    runtime_dir: Path, requirements: Path, extra_requirements: list[str]
) -> None:
    python_exe = runtime_dir / "python.exe"
    run([str(python_exe), "-m", "pip", "install", "--upgrade", "pip"])
    if requirements.exists():
        run([str(python_exe), "-m", "pip", "install", "-r", str(requirements)])
    for requirement in extra_requirements:
        run([str(python_exe), "-m", "pip", "install", requirement])


def write_manifest(runtime_dir: Path, version: str, arch: str) -> None:
    manifest = runtime_dir / "HAKUREI_RUNTIME.txt"
    manifest.write_text(
        f"HakureiTerminal Windows embeddable CPython runtime\n"
        f"Python: {version}\n"
        f"Arch: {arch}\n"
        f"Generated by: scripts/prepare_windows_runtime.py\n",
        encoding="utf-8",
    )


def prepare(
    version: str,
    arch: str,
    cache_dir: Path,
    target: Path,
    requirements: Path,
    extra_requirements: list[str],
    clean: bool,
    skip_pip_install: bool,
) -> None:
    archive = cache_dir / f"python-{version}-embed-{arch}.zip"
    download(embeddable_url(version, arch), archive)
    extract_runtime(archive, target, clean=clean)
    enable_site(target)
    if not skip_pip_install:
        bootstrap_pip(target, cache_dir)
        install_requirements(target, requirements, extra_requirements)
    write_manifest(target, version, arch)
    print(f"Prepared Windows CPython runtime at {target}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare Windows embeddable CPython runtime")
    parser.add_argument("--version", default=DEFAULT_VERSION)
    parser.add_argument("--arch", default=DEFAULT_ARCH, choices=["amd64", "win32", "arm64"])
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR)
    parser.add_argument("--target", type=Path, default=DEFAULT_TARGET)
    parser.add_argument("--requirements", type=Path, default=ROOT / "requirements.txt")
    parser.add_argument(
        "--extra-requirement",
        action="append",
        default=[],
        help="Additional requirement to install into the embedded runtime. May be repeated.",
    )
    parser.add_argument("--no-clean", action="store_true")
    parser.add_argument("--skip-pip-install", action="store_true")
    return parser.parse_args()


def main() -> None:
    if sys.platform != "win32":
        raise SystemExit("This script prepares the Windows runtime and must run on Windows.")
    args = parse_args()
    prepare(
        version=args.version,
        arch=args.arch,
        cache_dir=args.cache_dir.resolve(),
        target=args.target.resolve(),
        requirements=args.requirements.resolve(),
        extra_requirements=args.extra_requirement,
        clean=not args.no_clean,
        skip_pip_install=args.skip_pip_install,
    )


if __name__ == "__main__":
    main()
